FROM flexberry/clickhouse-official

EXPOSE 8123
EXPOSE 9000

#COPY ./docker/clickhouse/configs/config.xml /etc/clickhouse-server/config.xml
#COPY ./docker/clickhouse/configs/users.xml /etc/clickhouse-server/users.xml
#ADD init/init-db.sql /docker-entrypoint-initdb.d/
#COPY ./docker/clickhouse/init/ /docker-entrypoint-initdb.d/