version: "3.8"

services:
  mariadb:
    build:
      context: ./
      dockerfile: docker/mariadb/Dockerfile
      args:
        CURRENT_USER: ${CURRENT_USER}
    image: ${COMPOSE_PROJECT_NAME}_mariadb
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb_1
    volumes:
      - mariadb-data-server:/var/lib/mysql:rw
    networks:
      - project-network