version: "3.8"

services:
  clickhouse:
    build:
      context: ./
      dockerfile: docker/clickhouse/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_clickhouse
    container_name: ${COMPOSE_PROJECT_NAME}_clickhouse_1
    volumes:
      - clickhouse-db-data:/var/lib/clickhouse
    networks:
      - project-network